//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfEditID;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlTopic;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTopic;
        protected global::System.Web.UI.WebControls.TextBox txtSummary;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSummary;
        protected global::System.Web.UI.WebControls.TextBox txtContent;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContent;
        protected global::System.Web.UI.WebControls.TextBox txtSortOrder;
        protected global::System.Web.UI.WebControls.RangeValidator rvSortOrder;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.GridView gvMaterials;
    }
}
