//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class Index
    {
        protected global::System.Web.UI.WebControls.Panel pnlGuestCTA;
    }
}
