//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class ManageQuiz
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfEditID;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuiz;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuiz;
        protected global::System.Web.UI.WebControls.TextBox txtQuestion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuestion;
        protected global::System.Web.UI.WebControls.TextBox txtOptA;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOptA;
        protected global::System.Web.UI.WebControls.TextBox txtOptB;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOptB;
        protected global::System.Web.UI.WebControls.TextBox txtOptC;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOptC;
        protected global::System.Web.UI.WebControls.TextBox txtOptD;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOptD;
        protected global::System.Web.UI.WebControls.RadioButton rbA;
        protected global::System.Web.UI.WebControls.RadioButton rbB;
        protected global::System.Web.UI.WebControls.RadioButton rbC;
        protected global::System.Web.UI.WebControls.RadioButton rbD;
        protected global::System.Web.UI.WebControls.CustomValidator cvCorrectAns;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.GridView gvQuestions;
    }
}
