//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class QuizList
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litWelcome;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.Label lblNoQuiz;
    }
}
