//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class QuizAttempt
    {
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litTopic;
        protected global::System.Web.UI.WebControls.HiddenField hfTimer;
        protected global::System.Web.UI.WebControls.Literal litTotalQ;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
