//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class QuizResult
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litTopic;
        protected global::System.Web.UI.WebControls.Literal litPercentage;
        protected global::System.Web.UI.WebControls.Literal litScore;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litWrong;
        protected global::System.Web.UI.WebControls.Label lblPassFail;
        protected global::System.Web.UI.WebControls.HyperLink lnkTryAgain;
        protected global::System.Web.UI.WebControls.Repeater rptReview;
    }
}
