//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liRegister;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLogin;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liAdmin;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liManageQuiz;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liWelcome;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLogout;
        protected global::System.Web.UI.WebControls.Literal litWelcome;
    }
}
