//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduConnect
{
    public partial class StudyMaterials
    {
        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnAll;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnHtml;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnCss;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Literal litListHeading;
        protected global::System.Web.UI.WebControls.Label lblListError;
        protected global::System.Web.UI.WebControls.Repeater rptMaterials;
        protected global::System.Web.UI.WebControls.Label lblNoData;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Literal litDetailTopic;
        protected global::System.Web.UI.WebControls.Literal litDetailTitle;
        protected global::System.Web.UI.WebControls.Literal litDetailDate;
        protected global::System.Web.UI.WebControls.Literal litDetailContent;
    }
}
